baseurl = "websites"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Jane Doe"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Ahmed Aboushama"
author = "Ahmed Aboushama"
description = "Administrative Assistant"
profilePicture = "images/photo_of_,me.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/ahmednasrat"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/ahmednasrat94/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:ahmed_nasrat@outlook.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"